var data= [
	{country:"Russia",Region:"Eastern Europe",Deaths:55736,Affected:null,Damages:400,"Year":2010,Development:4,Severity:92},
	{country:"Belgium",Region:"Western Europe",Deaths:940,Affected:null,Damages:null,"Year":2006,Development:5,Severity:61},
	{country:"Austria",Region:"Western Europe",Deaths:345,Affected:null,Damages:280,"Year":2003,Development:5,Severity:62},
	{country:"Slovenia",Region:"Eastern Europe",Deaths:289,Affected:null,Damages:80,"Year":2003,Development:5,Severity:62},
	{country:"Greece",Region:"Western Europe",Deaths:16,Affected:null,Damages:null,"Year":2007,Development:5,Severity:61},
	{country:"Turkey",Region:"Western Europe",Deaths:11,Affected:300,Damages:1,"Year":2000,Development:4,Severity:61},
	{country:"Japan",Region:"Asia",Deaths:10,Affected:300,Damages:null,"Year":2004,Development:5,Severity:62},
	{country:"India",Region:"Asia",Deaths:1210,Affected:null,Damages:400,"Year":2003,Development:1,Severity:24},
	{country:"Italy",Region:"Western Europe",Deaths:20089,Affected:null,Damages:4400,"Year":2003,Development:5,Severity:31},
	{country:"France",Region:"Western Europe",Deaths:19490,Affected:null,Damages:4400,"Year":2003,Development:5,Severity:20},
	{country:"India",Region:"Asia",Deaths:1030,Affected:null,Damages:null,"Year":2002,Development:1,Severity:13},
	{country:"Germany",Region:"Western Europe",Deaths:9355,Affected:null,Damages:1650,"Year":2003,Development:5,Severity:31},
	{country:"Portugal",Region:"Western Europe",Deaths:2696,Affected:null,Damages:null,"Year":2003,Development:5,Severity:31},
	{country:"Switzerland",Region:"Western Europe",Deaths:1039,Affected:null,Damages:280,"Year":2003,Development:5,Severity:31},
	{country:"Croatia",Region:"Eastern Europe",Deaths:788,Affected:null,Damages:null,"Year":2003,Development:4,Severity:31},
	{country:"Hungary",Region:"Eastern Europe",Deaths:500,Affected:null,Damages:null,"Year":2007,Development:4,Severity:31},
	{country:"Czech Republic",Region:"Eastern Europe",Deaths:418,Affected:null,Damages:null,"Year":2003,Development:5,Severity:31},
	{country:"United Kingdom",Region:"Western Europe",Deaths:301,Affected:null,Damages:null,"Year":2003,Development:5,Severity:31},
	{country:"Luxembourg",Region:"Western Europe",Deaths:170,Affected:null,Damages:null,"Year":2003,Development:5,Severity:31},
	{country:"India",Region:"Asia",Deaths:329,Affected:null,Damages:null,"Year":2005,Development:2,Severity:30},
	{country:"United States",Region:"North America",Deaths:164,Affected:null,Damages:null,"Year":2006,Development:5,Severity:33},
	{country:"Japan",Region:"Asia",Deaths:62,Affected:3000,Damages:null,"Year":2007,Development:5,Severity:17},
	{country:"Russia",Region:"Eastern Europe",Deaths:276,Affected:null,Damages:null,"Year":2001,Development:3,Severity:31},
	{country:"India",Region:"Asia",Deaths:250,Affected:null,Damages:null,"Year":2010,Development:2,Severity:92},
	{country:"Pakistan",Region:"Middle East",Deaths:200,Affected:null,Damages:null,"Year":2003,Development:1,Severity:37},
	{country:"United States",Region:"North America",Deaths:56,Affected:null,Damages:null,"Year":2001,Development:5,Severity:31},
	{country:"Portugal",Region:"Western Europe",Deaths:41,Affected:null,Damages:null,"Year":2006,Development:5,Severity:31},
	{country:"Croatia",Region:"Eastern Europe",Deaths:40,Affected:200,Damages:240,"Year":2000,Development:4,Severity:30},
	{country:"India",Region:"Asia",Deaths:120,Affected:25,Damages:null,"Year":2009,Development:2,Severity:74},
	{country:"Pakistan",Region:"Middle East",Deaths:113,Affected:24,Damages:null,"Year":2002,Development:1,Severity:31},
	{country:"Pakistan",Region:"Middle East",Deaths:106,Affected:200,Damages:null,"Year":2005,Development:1,Severity:16},
	{country:"Pakistan",Region:"Middle East",Deaths:84,Affected:100,Damages:null,"Year":2006,Development:1,Severity:31},
	{country:"India",Region:"Asia",Deaths:72,Affected:null,Damages:null,"Year":2007,Development:2,Severity:91},
	{country:"United States",Region:"North America",Deaths:35,Affected:null,Damages:null,"Year":2000,Development:5,Severity:31},
	{country:"Bangladesh",Region:"Asia",Deaths:62,Affected:null,Damages:null,"Year":2003,Development:1,Severity:34},
	{country:"Nigeria",Region:"Africa",Deaths:60,Affected:null,Damages:null,"Year":2002,Development:1,Severity:30},
	{country:"United States",Region:"North America",Deaths:33,Affected:31,Damages:null,"Year":2005,Development:5,Severity:27},
	{country:"India",Region:"Asia",Deaths:47,Affected:null,Damages:null,"Year":2006,Development:2,Severity:31},
	{country:"Brazil",Region:"Latin America and the Caribbeans",Deaths:32,Affected:null,Damages:null,"Year":2010,Development:4,Severity:28},
	{country:"Greece",Region:"Western Europe",Deaths:27,Affected:176,Damages:3,"Year":2000,Development:5,Severity:31},
	{country:"Algeria",Region:"Africa",Deaths:40,Affected:null,Damages:null,"Year":2003,Development:2,Severity:31},
	{country:"China",Region:"Asia",Deaths:39,Affected:null,Damages:null,"Year":2004,Development:2,Severity:2},
	{country:"United States",Region:"North America",Deaths:14,Affected:null,Damages:null,"Year":2002,Development:5,Severity:30},
	{country:"Cyprus",Region:"Middle East",Deaths:5,Affected:400,Damages:null,"Year":2000,Development:5,Severity:31},
	{country:"Spain",Region:"Western Europe",Deaths:15090,Affected:null,Damages:880,"Year":2003,Development:5,Severity:11},
	{country:"Romania",Region:"Eastern Europe",Deaths:30,Affected:null,Damages:null,"Year":2007,Development:3,Severity:61},
	{country:"Romania",Region:"Eastern Europe",Deaths:27,Affected:null,Damages:null,"Year":2004,Development:3,Severity:31},
	{country:"France",Region:"Western Europe",Deaths:1388,Affected:null,Damages:null,"Year":2006,Development:5,Severity:9},
	{country:"Romania",Region:"Eastern Europe",Deaths:26,Affected:200,Damages:null,"Year":2006,Development:3,Severity:33},
	{country:"Belgium",Region:"Western Europe",Deaths:1175,Affected:null,Damages:null,"Year":2003,Development:5,Severity:15},
	{country:"Pakistan",Region:"Middle East",Deaths:24,Affected:null,Damages:null,"Year":2000,Development:1,Severity:30},
	{country:"Netherlands",Region:"Western Europe",Deaths:1000,Affected:null,Damages:null,"Year":2006,Development:5,Severity:9},
	{country:"Netherlands",Region:"Western Europe",Deaths:965,Affected:null,Damages:null,"Year":2003,Development:5,Severity:14},
	{country:"Australia",Region:"South Pacific",Deaths:347,Affected:2000,Damages:null,"Year":2009,Development:5,Severity:13},
	{country:"Republic of Macedonia",Region:"Eastern Europe",Deaths:15,Affected:null,Damages:null,"Year":2004,Development:3,Severity:31},
	{country:"Japan",Region:"Asia",Deaths:170,Affected:15000,Damages:null,"Year":2010,Development:5,Severity:7},
	{country:"Canary Islands",Region:"Western Europe",Deaths:13,Affected:113,Damages:null,"Year":2004,Development:null,Severity:5},
	{country:"Romania",Region:"Eastern Europe",Deaths:13,Affected:500,Damages:null,"Year":2005,Development:3,Severity:6},
	{country:"Spain",Region:"Western Europe",Deaths:26,Affected:null,Damages:null,"Year":2004,Development:5,Severity:5},
	{country:"United States",Region:"North America",Deaths:24,Affected:null,Damages:null,"Year":2006,Development:5,Severity:8},
	{country:"China",Region:"Asia",Deaths:7,Affected:3500,Damages:null,"Year":2002,Development:2,Severity:31},
	{country:"Romania",Region:"Eastern Europe",Deaths:6,Affected:100,Damages:null,"Year":2000,Development:3,Severity:31},
	{country:"Spain",Region:"Western Europe",Deaths:21,Affected:null,Damages:null,"Year":2006,Development:5,Severity:9},
	{country:"Albania",Region:"Eastern Europe",Deaths:null,Affected:150,Damages:null,"Year":2007,Development:2,Severity:8},
	{country:"China",Region:"Asia",Deaths:null,Affected:200,Damages:null,"Year":2005,Development:2,Severity:31},
	{country:"Republic of Macedonia",Region:"Eastern Europe",Deaths:null,Affected:202,Damages:null,"Year":2007,Development:3,Severity:31}
];